import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:analyzer/dart/element/visitor2.dart';
import 'package:source_gen/source_gen.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';

import 'analysis.dart';
import 'fields_visitor_config.dart';
import 'symbols/field_info.dart';

/// Collects the fields of [element] together with the fields it inherits.
///
/// Only the superclass chain and the applied mixins contribute: an interface
/// reached through `implements` has to be satisfied by [element] itself, so
/// its declarations would shadow nothing and cannot be constructed.
///
/// Types are visited in Dart's own resolution order — the class first, then
/// its mixins from last applied to first, then the superclass chain — and the
/// first declaration of a name wins, so the declaration actually in effect is
/// the one that is collected.
///
/// The [config] controls what information is collected for each field.
List<FieldInfo> collectFields(
  ClassElement element, {
  FieldsVisitorConfig config = const FieldsVisitorConfig(),
}) {
  final visitor = FieldsVisitor(config: config);

  element.visitChildren(visitor);

  for (final inherited in _inheritedTypes(element.thisType)) {
    inherited.element.visitChildren(visitor);
  }

  return visitor.fields;
}

/// Yields the types [type] inherits members from, nearest first.
Iterable<InterfaceType> _inheritedTypes(InterfaceType type) sync* {
  // A mixin is applied on top of the superclass, so a member it declares wins
  // over the same member further up the chain. The last mixin applied wins
  // over the ones before it.
  yield* type.mixins.reversed;

  final superclass = type.superclass;

  if (superclass != null && !superclass.isDartCoreObject) {
    yield superclass;
    yield* _inheritedTypes(superclass);
  }
}

/// A visitor that collects field information from a class element.
///
/// This visitor traverses class elements and extracts information about their
/// fields, converting them into [FieldInfo] objects. Fields annotated with
/// `@ignore` are excluded from the collection.
///
/// The visitor only processes non-synthetic fields (fields that are explicitly
/// declared in the source code, not generated by the compiler).
///
/// Example usage:
/// ```dart
/// // FieldsVisitorConfig config (default)
/// final visitor = FieldsVisitor();
/// classElement.visitChildren(visitor);
/// final fields = visitor.fields;
/// ```
class FieldsVisitor extends SimpleElementVisitor2<void> {
  /// Creates a [FieldsVisitor] with the specified [config].
  ///
  /// The [config] controls what information should be collected during field
  /// visiting.
  FieldsVisitor({this.config = const FieldsVisitorConfig()});

  /// Configuration controlling what information to collect.
  ///
  /// See [FieldsVisitorConfig] for available options and presets.
  final FieldsVisitorConfig config;

  /// Collected field information, keyed by field name.
  ///
  /// Keying by name means a redeclared field is collected once. The first
  /// declaration seen wins; see [collectFields] for the visiting order that
  /// makes the nearest declaration the first one.
  final Map<String, FieldInfo> _fields = {};

  /// Names already decided on, including the ones that were skipped.
  ///
  /// An `@ignore` on a redeclaration has to suppress the inherited
  /// declaration too, so a skipped name still claims its place.
  final Set<String> _claimed = {};

  /// Returns an immutable list of collected field information.
  ///
  /// The list is created from the internal map, preserving the order in which
  /// the fields were visited and preventing external modification.
  List<FieldInfo> get fields => _fields.values.toList(growable: false);

  /// Type checker used to identify fields annotated with `@ignore`.
  ///
  /// Fields with this annotation will be skipped during the visit.
  final ignoreAnnotationTypeChecker = TypeChecker.typeNamed(ignore.runtimeType);

  /// Visits a field element and collects its information if applicable.
  ///
  /// The field is added to the collection if:
  /// - It is not annotated with `@ignore`
  /// - It is not synthetic (compiler-generated)
  ///
  /// Synthetic fields are typically generated for getters/setters and should
  /// not be included in the collected field information.
  @override
  void visitFieldElement(FieldElement element) {
    // Only process non-synthetic fields (explicitly declared in source code)
    if (!element.isOriginDeclaration) {
      return;
    }

    // A private field cannot be passed to a generated constructor call, and a
    // private name is not a valid named parameter either.
    if (element.isPrivate) {
      return;
    }

    final name = element.displayName;

    if (!_claimed.add(name)) {
      return;
    }

    // Skip fields annotated with @ignore
    if (ignoreAnnotationTypeChecker.hasAnnotationOf(element)) {
      return;
    }

    _fields[name] = fieldSymbol(element, config: config);
  }
}
