import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/visitor2.dart';
import 'package:source_gen/source_gen.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';

import 'analysis.dart';
import 'fields_visitor_config.dart';
import 'symbols/field_info.dart';

/// Collects the fields of [element] together with the fields of all its
/// supertypes.
///
/// Supertypes are visited first, so a field redeclared by [element] replaces
/// the inherited one. The [config] controls what information is collected for
/// each field.
List<FieldInfo> collectFields(
  ClassElement element, {
  FieldsVisitorConfig config = const FieldsVisitorConfig(),
}) {
  final visitor = FieldsVisitor(config: config);

  for (final supertype in element.allSupertypes) {
    if (!supertype.isDartCoreObject) {
      supertype.element.visitChildren(visitor);
    }
  }

  element.visitChildren(visitor);

  return visitor.fields;
}

/// A visitor that collects field information from a class element.
///
/// This visitor traverses class elements and extracts information about their
/// fields, converting them into [FieldInfo] objects. Fields annotated with
/// `@ignore` are excluded from the collection.
///
/// The visitor only processes non-synthetic fields (fields that are explicitly
/// declared in the source code, not generated by the compiler).
///
/// Example usage:
/// ```dart
/// // FieldsVisitorConfig config (default)
/// final visitor = FieldsVisitor();
/// classElement.visitChildren(visitor);
/// final fields = visitor.fields;
/// ```
class FieldsVisitor extends SimpleElementVisitor2<void> {
  /// Creates a [FieldsVisitor] with the specified [config].
  ///
  /// The [config] controls what information should be collected during field
  /// visiting.
  FieldsVisitor({this.config = const FieldsVisitorConfig()});

  /// Configuration controlling what information to collect.
  ///
  /// See [FieldsVisitorConfig] for available options and presets.
  final FieldsVisitorConfig config;

  /// Collected field information, keyed by field name.
  ///
  /// Keying by name means a field redeclared by a subclass replaces the one
  /// declared by its supertype instead of being collected twice.
  final Map<String, FieldInfo> _fields = {};

  /// Returns an immutable list of collected field information.
  ///
  /// The list is created from the internal map, preserving the order in which
  /// the fields were visited and preventing external modification.
  List<FieldInfo> get fields => _fields.values.toList(growable: false);

  /// Type checker used to identify fields annotated with `@ignore`.
  ///
  /// Fields with this annotation will be skipped during the visit.
  final ignoreAnnotationTypeChecker = TypeChecker.typeNamed(ignore.runtimeType);

  /// Visits a field element and collects its information if applicable.
  ///
  /// The field is added to the collection if:
  /// - It is not annotated with `@ignore`
  /// - It is not synthetic (compiler-generated)
  ///
  /// Synthetic fields are typically generated for getters/setters and should
  /// not be included in the collected field information.
  @override
  void visitFieldElement(FieldElement element) {
    // Skip fields annotated with @ignore
    if (ignoreAnnotationTypeChecker.hasAnnotationOf(element)) {
      return;
    }

    // Only process non-synthetic fields (explicitly declared in source code)
    if (element.isOriginDeclaration) {
      _fields[element.displayName] = fieldSymbol(element, config: config);
    }
  }
}
