import 'package:analyzer/dart/element/element.dart';
import 'package:source_gen/source_gen.dart';
import 'package:theme_extensions_builder_annotation/theme_extensions_builder_annotation.dart';

import 'analysis.dart';
import 'base_class_visiter.dart';
import 'symbols/field_info.dart';

/// A visitor that collects field information from a class element.
///
/// This visitor traverses class elements and extracts information about their
/// fields, converting them into [FieldInfo] objects. Fields annotated with
/// `@ignore` are excluded from the collection.
///
/// The visitor only processes non-synthetic fields (fields that are explicitly
/// declared in the source code, not generated by the compiler).
///
/// Example usage:
/// ```dart
/// final visitor = FieldsVisitor();
/// classElement.visitChildren(visitor);
/// final fields = visitor.fields;
/// ```
class FieldsVisitor extends BaseClassVisitor {
  /// Internal set to store unique field information.
  final Set<FieldInfo> _fields = {};

  /// Returns an immutable list of collected field information.
  ///
  /// The list is created from the internal set, ensuring no duplicates
  /// and preventing external modification.
  List<FieldInfo> get fields => _fields.toList(growable: false);

  /// Type checker used to identify fields annotated with `@ignore`.
  ///
  /// Fields with this annotation will be skipped during the visit.
  final ignoreAnnotationTypeChecker = TypeChecker.typeNamed(ignore.runtimeType);

  /// Visits a field element and collects its information if applicable.
  ///
  /// The field is added to the collection if:
  /// - It is not annotated with `@ignore`
  /// - It is not synthetic (compiler-generated)
  ///
  /// Synthetic fields are typically generated for getters/setters and should
  /// not be included in the collected field information.
  @override
  void visitFieldElement(FieldElement element) {
    // Skip fields annotated with @ignore
    if (ignoreAnnotationTypeChecker.hasAnnotationOf(element)) {
      return;
    }

    // Only process explicitly declared fields
    if (!element.isSynthetic) {
      final field = fieldSymbol(element);
      _fields.add(field);
    }
  }
}
