name: theme_extensions_builder_annotation
description:
>
  Annotations for the theme_extensions_builder.
  This package does nothing without theme_extensions_builder.

repository: https://github.com/pro100andrey/theme_extensions_builder
issue_tracker: https://github.com/pro100andrey/theme_extensions_builder/issues
homepage: https://github.com/pro100andrey/theme_extensions_builder
documentation: https://github.com/pro100andrey/theme_extensions_builder/blob/main/packages/theme_extensions_builder/README.md

version: 5.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.8.1

dependencies:
  meta: ^1.16.0

dev_dependencies:
  pro_lints: ^4.0.0
